DeepscribeConfig:
    language: en
    decoder:
        lm_path: /share/models/english/financial-0.1.3.trie
        lm_workers: 2
    model:
        model_path: /share/models/english/deepscribe-0.3.0.pth
    text_postprocessing:
        punc_path: /share/models/english/punc-0.2.0.pth
        acronyms_path: /share/models/english/acronyms/all.acronyms.txt
