DeepscribeConfig:
    language: en
    decoder:
        lm_path: models/financial-0.1.3.trie
        lm_workers: 2
    model:
        model_path: models/deepscribe-0.3.0.pth
    text_postprocessing:
        punc_path: models/punc-0.2.0.pth
        acronyms_path: models/all.acronyms.txt
