transcriber: deepscribe
# Dev environment locations - change for deployment
model_path: "/share/models/french/deepscribe-fr-0.1.2.pth"
lm_path: "/share/models/french/french-0.1.0.trie"
punc_path: "/share/models/french/punc-fr-0.1.0.pth"
acronyms_path: 
lm_alpha: 0.39
lm_beta: 0.45
device: cuda