name: Build and publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      CI_TOOLS: ./ci-tools
      bamboo_hudson_artifactory_key_secret: ${{ secrets.bamboo_hudson_artifactory_key_secret }}
      
    steps:

    - name: Checkout this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}
      
    - name: Checkout build tools repo
      uses: actions/checkout@v2
      with:
        repository:  Smarsh/build-tools 
        path: ci-tools

    - name: Build
      run: ./ci-tools/package-all.sh
