name: Master Tests

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Artifactory Configuration
      uses: jfrog/setup-jfrog-cli@v2
      env:
        JF_ARTIFACTORY_1: ${{secrets.JF_ARTIFACTORY_SECRET_1}}

    - name: System Configuration
      run: |
        python3 -m pip install --upgrade pip

        chmod +x scripts/system_setup.sh
        chmod +x scripts/test.sh

        ./scripts/system_setup.sh

    - name: Code Coverage Report
      run: |
        sudo apt-get update
        ./scripts/download_test_data.sh
        ./scripts/download_english_models.sh
        ./scripts/test.sh

    - name: Setup Sonarqubescanner
      uses: warchant/setup-sonar-scanner@v3

    - name: SonarCloud Scan
      run: |
        pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        sonar-scanner -Dsonar.host.url=${{secrets.SONAR_URL}} -Dsonar.projectKey=transcriber-api  -Dsonar.sources=/home/runner/work/transcriber-api/transcriber-api  -Dsonar.login=${{secrets.SONAR_KEY}} -Dsonar.github.repository=Smarsh/transcriber-api  -Dsonar.github.oauth=${{secrets.G_ACCESS_TOKEN}} -Dsonar.analysis.mode=preview -Dsonar.github.pullRequest=$pr_number