name: Pull Request

on:
  pull_request:
    branches:
    - master
    
jobs:
  launchDarklyCodeReferences:
    name: Check for Secrets
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: trufflehog-actions-scan
      uses: UnicornGlobal/trufflehog-actions-scan@master
